apiVersion: v1
kind: Secret
metadata: 
  name: azure-storage-account
stringData:
  server-url: https://<account_name>.blob.core.windows.net
---
apiVersion: v1
kind: Secret
metadata: 
  name: azure-management-api
stringData:
  server-url: https://management.azure.com