apiVersion: finops.krateo.io/v1
kind: ExporterScraperConfig
metadata:
  name: exporterscraperconfig-sample
  namespace: krateo-system
spec:
  exporterConfig:
    api: 
      path: /<container>/<directory>/<file_name>
      verb: GET
      headers:
      - "x-ms-version: 2017-11-09"
      endpointRef:
        name: azure-storage-account
        namespace: krateo-system
    metricType: cost
    pollingInterval: "1h"
    additionalVariables:
      account_name: # Your storage account name, compiled into the endpoint azure-storage-account
      # These values could be different depending on how you setup your FOCUS export and logic app
      container: focus
      directory: exports
      file_name: static-export.csv
  scraperConfig:
    pollingInterval: "1h"
    tableName: finops # This table is used for costs and can be customized; resources usage will go in <table_name>_res
    scraperDatabaseConfigRef: # This config is created by the krateo-installer
      name: finops-database-handler
      namespace: krateo-system