## ----- external-secrets operator configuration  ----- 
## ----------------------------------------------------
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: azure-token-secret-management
  namespace: krateo-system
spec:
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: azure-token-store-management
      kind: ClusterSecretStore
    target:
      name: azure-management-api
      creationPolicy: Merge
    data:
      - secretKey: token
        remoteRef:
          key: access_token
          property: access_token
  # This is required for ClusterExternalSecret to know which namespaces to create the secret in
  namespaceSelector:
    matchLabels:
      azure-secrets: enabled
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: azure-token-secret-storage
  namespace: krateo-system
spec:
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: azure-token-store-storage
      kind: ClusterSecretStore
    target:
      name: azure-storage-account
      creationPolicy: Merge
    data:
      - secretKey: token
        remoteRef:
          key: access_token
          property: access_token
  # This is required for ClusterExternalSecret to know which namespaces to create the secret in
  namespaceSelector:
    matchLabels:
      azure-secrets: enabled
---
# The external secret to request the bearer token to access usage metrics
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-token-store-management
  namespace: krateo-system
spec:
  provider:
    webhook:
      url: "https://login.microsoftonline.com/{{ .Values.tenantId }}/oauth2/token?"
      method: "POST"
      body: "grant_type=client_credentials&client_id={{ "{{" }} .client_id.clientId }}&client_secret={{ "{{" }} .client_secret.clientSecret {{ "}}" }}&resource=https://management.azure.com"
      headers:
        Content-Type: "application/x-www-form-urlencoded"
      result:
        jsonPath: "$.access_token"
      secrets:
        - name: client_id
          secretRef:
            name: azcli-id
            key: clientId
            namespace: krateo-system
        - name: client_secret
          secretRef:
            name: azcli-sec
            key: clientSecret
            namespace: krateo-system
      timeout: "30s"
---
# The external secret to request the bearer token to access the storage account
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-token-store-storage
  namespace: krateo-system
spec:
  provider:
    webhook:
      url: "https://login.microsoftonline.com/{{ .Values.tenantId }}/oauth2/token?"
      method: "POST"
      body: "grant_type=client_credentials&client_id={{ "{{" }} .client_id.clientId {{ "}}" }}&client_secret={{ "{{" }} .client_secret.clientSecret {{ "}}" }}&resource=https://storage.azure.com"
      headers:
        Content-Type: "application/x-www-form-urlencoded"
      result:
        jsonPath: "$.access_token"
      secrets:
        - name: client_id
          secretRef:
            name: azcli-id
            key: clientId
            namespace: krateo-system
        - name: client_secret
          secretRef:
            name: azcli-sec
            key: clientSecret
            namespace: krateo-system
      timeout: "30s"