apiVersion: v1
kind: Secret
metadata: 
  name: azcli-id
  labels:
    external-secrets.io/type: webhook
stringData:
  clientId: {{ .Values.clientId }}
---
apiVersion: v1
kind: Secret
metadata: 
  name: azcli-sec
  labels:
    external-secrets.io/type: webhook
stringData:
  clientSecret: {{ .Values.clientSecret }}